#!/usr/bin/perl

use strict;
use warnings;
use DBI;

my $user = "root";
my $pass = "password";
my $db = "information_schema";

my $dbh = DBI->connect("DBI:mysql:$db", $user, $pass)
        or die "Connection error: $DBI::errstr\n";
my $sql = "show processlist";


my $sth = $dbh->prepare($sql);
$sth->execute() or die "SQL error: $DBI::errstr\n";

my %user;

while (my @row = $sth->fetchrow_array()) {
        $user{$row[1]}++;
}

print "MySQL - Logged in users\n";
print "=" x 15, "\n";

for my $x (keys %user) {
        print "$x - $user{$x} connections\n";
}
